### ISSUE TITLE
Homepage font scaling on iOS Mobile at 100% overwrites text

### ISSUE THREAD

**Issue by OftKilted** [jsc17/Terminals-BT#60]
On mobile devices the text has bad overlap when set to 100% font scaling on iOS. 

Example of page at 100% font scaling
![IMG_7050](https://github.com/user-attachments/assets/bbdd4cf3-28c7-4443-87b3-15774a46ae6d)

Font scaling must be dropped to 50% to view all text without page distortion and overlap.

Example of page At 50% font scaling:
![IMG_7051](https://github.com/user-attachments/assets/b62caa2a-8607-4aa2-a5f3-add0c5a69e9e)

**Comment by jsc17** [comment]
height issue fixed by 7019652
